# Generated by Django 4.2.20 on 2025-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_order_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("wedding", "Wedding Cakes"),
                    ("birthday", "Birthday Cakes"),
                    ("kids", "Kids Cakes"),
                    ("custom", "Custom Designs"),
                    ("muffins", "Muffins"),
                    ("cupcakes", "Cupcakes"),
                    ("scones", "Scones"),
                    ("party_packs", "Party Packs"),
                    ("balloons", "Balloon Garlands"),
                    ("specials", "Specials"),
                ],
                default="custom",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
