# Generated by Django 4.2.20 on 2025-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_galleryimage_options_alter_menuitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="category",
            field=models.CharField(
                choices=[
                    ("wedding", "Wedding Cakes"),
                    ("birthday", "Birthday Cakes"),
                    ("kids", "Kids Cakes"),
                    ("custom", "Custom Designs"),
                    ("muffins", "Muffins"),
                    ("cupcakes", "Cupcakes"),
                    ("scones", "Scones"),
                    ("party_packs", "Party Packs"),
                    ("balloons", "Balloon Garlands"),
                    ("specials", "Specials"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("wedding", "Wedding Cakes"),
                    ("birthday", "Birthday Cakes"),
                    ("kids", "Kids Cakes"),
                    ("custom", "Custom Designs"),
                    ("muffins", "Muffins"),
                    ("cupcakes", "Cupcakes"),
                    ("scones", "Scones"),
                    ("party_packs", "Party Packs"),
                    ("balloons", "Balloon Garlands"),
                    ("specials", "Specials"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
    ]
